### ISSUE TITLE
invalid user/pass

### ISSUE THREAD

**Issue by ngouy** [talmobi/tor-request#39] opened 2019-01-11 20:54 UTC
fresh install on osx :

`brew install tor` -> ok
`tor` -> ok
`npm install tor-request` -> ok
with your exemple : 
```js
# index.js

var tr = require('tor-request');
tr.request('https://api.ipify.org', function (err, res, body) {
  if (!err && res.statusCode == 200) {
    console.log("Your public (through Tor) IP is: " + body);
  }
});
```

`node index.js` -> fail

tor logs

socks5: parsing failed - invalid user/pass authentication message.

**Comment by talmobi** [comment] 2019-01-12 13:04
It's working fine for me. Can you print your `tor´ version (installed by brew) and `tor-request` module in your package.json?

To get tor version installed by brew do this:
`tor --version`

**Comment by ngouy** [comment] 2019-01-14 14:54
Tor : 0.3.5.7
tor-request : 2.3.0

**Comment by ngouy** [comment] 2019-01-14 14:57
logs
(node -v -> v8.12.0)

```
➜  ~ tor
Jan 14 09:55:28.462 [notice] Tor 0.3.5.7 running on Darwin with Libevent 2.1.8-stable, OpenSSL 1.0.2q, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Jan 14 09:55:28.462 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jan 14 09:55:28.463 [notice] Configuration file "/usr/local/etc/tor/torrc" not present, using reasonable defaults.
Jan 14 09:55:28.468 [notice] Opening Socks listener on 127.0.0.1:9050
Jan 14 09:55:28.468 [notice] Opened Socks listener on 127.0.0.1:9050
Jan 14 09:55:28.000 [notice] Parsing GEOIP IPv4 file /usr/local/Cellar/tor/0.3.5.7_1/share/tor/geoip.
Jan 14 09:55:28.000 [notice] Parsing GEOIP IPv6 file /usr/local/Cellar/tor/0.3.5.7_1/share/tor/geoip6.
Jan 14 09:55:28.000 [notice] Bootstrapped 0%: Starting
Jan 14 09:55:29.000 [notice] Starting with guard context "default"
Jan 14 09:55:29.000 [notice] Bootstrapped 5%: Connecting to directory server
Jan 14 09:55:29.000 [notice] Bootstrapped 10%: Finishing handshake with directory server
Jan 14 09:55:29.000 [notice] Bootstrapped 15%: Establishing an encrypted directory connection
Jan 14 09:55:29.000 [notice] Bootstrapped 20%: Asking for networkstatus consensus
Jan 14 09:55:29.000 [notice] Bootstrapped 50%: Loading relay descriptors
Jan 14 09:55:30.000 [notice] Bootstrapped 80%: Connecting to the Tor network
Jan 14 09:55:31.000 [notice] Bootstrapped 85%: Finishing handshake with first hop
Jan 14 09:55:31.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
Jan 14 09:55:32.000 [notice] Bootstrapped 100%: Done
```
```
node index.js
```
```
Jan 14 09:56:13.000 [warn] socks5: parsing failed - invalid user/pass authentication message.
Jan 14 09:56:13.000 [warn] Fetching socks handshake failed. Closing.
```

**Comment by talmobi** [comment] 2019-01-14 15:36
Halåj~

I can reproduce the issue.

This seems to be an issue with the latest version of `tor` (`3.5.7`) (less than a week old): https://trac.torproject.org/projects/tor/ticket/29050

In the mean time you can install a compatible version by editing the brew Formula manually:

`brew edit tor`

and copy paste in this Formula instead ( for version `3.2.10` )

```
class Tor < Formula
  desc "Anonymizing overlay network for TCP"
  homepage "https://www.torproject.org/"
  url "https://www.torproject.org/dist/tor-0.3.2.10.tar.gz"
  mirror "https://tor.eff.org/dist/tor-0.3.2.10.tar.gz"
  sha256 "60df77c31dcf94fdd686c8ca8c34f3b70243b33a7344ecc0b719d5ca2617cbee"

  bottle do
    sha256 "c9170852c7734a4703d60984d9394e5877a8d0346cad0e124565ede5fef154a4" => :high_sierra
    sha256 "29dc187af55647e455cfb5e7a62bc4da1316f7f1c753c387089d6a17a8940c40" => :sierra
    sha256 "6ccb7fbb44b052d4f6e5b3c27008d46a7772cc6a70266578b067e065ba9d59e3" => :el_capitan
  end

  depends_on "pkg-config" => :build
  depends_on "libevent"
  depends_on "openssl"
  depends_on "libscrypt" => :optional

  def install
    args = %W[
      --disable-dependency-tracking
      --disable-silent-rules
      --prefix=#{prefix}
      --sysconfdir=#{etc}
      --localstatedir=#{var}
      --with-openssl-dir=#{Formula["openssl"].opt_prefix}
    ]

    args << "--disable-libscrypt" if build.without? "libscrypt"

    system "./configure", *args
    system "make", "install"
  end

  plist_options :manual => "tor"

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
      <dict>
        <key>Label</key>
        <string>#{plist_name}</string>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
        <key>ProgramArguments</key>
        <array>
            <string>#{opt_bin}/tor</string>
        </array>
        <key>WorkingDirectory</key>
        <string>#{HOMEBREW_PREFIX}</string>
        <key>StandardErrorPath</key>
        <string>#{var}/log/tor.log</string>
        <key>StandardOutPath</key>
        <string>#{var}/log/tor.log</string>
      </dict>
    </plist>
    EOS
  end

  test do
    pipe_output("script -q /dev/null #{bin}/tor-gencert --create-identity-key", "passwd\npasswd\n")
    assert_predicate testpath/"authority_certificate", :exist?
    assert_predicate testpath/"authority_signing_key", :exist?
    assert_predicate testpath/"authority_identity_key", :exist?
  end
end
```

(this file is taken from `https://github.com/Homebrew/homebrew-core` by checking out commit `1dee625f4c9dd125321f47d91abe812bc6be3907`:

```
commit 1dee625f4c9dd125321f47d91abe812bc6be3907 (HEAD)
Author: BrewTestBot <brew-test-bot@googlegroups.com>
Date:   Sat Mar 3 15:03:22 2018 +0000

    tor: update 0.3.2.10 bottle.
```

`git clone https://github.com/Homebrew/homebrew-core`
`cd homebrew-core`
`git checkout 1dee625f4c9dd125321f47d91abe812bc6be3907`
`vim Formula/tor.rb`

**Comment by ngouy** [comment] 2019-01-14 15:37
👌 thanks

**Comment by talmobi** [comment] 2019-01-14 16:10
@ngouy published version 3.0.0 that defaults to socks type 4 which works around the socks5 not working on the latest tor version issue -- it also exposes `tr.proxySettings` where you can set the type yourself by `tr.proxySettings.type = 4`.

**Comment by ngouy** [comment] 2019-01-14 18:11
👍

**Comment by ngouy** [comment] 2019-01-14 18:12
Nice job, thank you for your help

**Comment by talmobi** [comment] 2019-01-20 18:15
@ngouy Can you close this issue if it's fixed for you? Thank you~

**Comment by knoxcard** [comment] 2019-01-21 18:20
@ngouy - close issue?

@talmobi - assuming it's okay to close issue on ngouy's behalf based  on the outstanding support you have provided.  If issues persist, ngouy can simply reopen ticket.

**Closed** 2019-01-21 19:12 UTC

**Comment by talmobi** [comment] 2019-01-27 03:34
https://github.com/torproject/tor/pull/670
